# Build stage
FROM rust:1.81 AS builder

WORKDIR /usr/src/app
COPY . .
RUN cargo build --release --bin image-transformer

# Image for image-transformer
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    imagemagick \
    inotify-tools && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /usr/src/app/target/release/image-transformer /app/

CMD ["./image-transformer"]
