version: '3'

services:
  immich-fetcher:
    build:
      context: .
      dockerfile: Dockerfile.immich-fetcher
    volumes:
      - ${ORIGINALS_DIR:-originals}:/app/originals
    environment:
      - IMMICH_URL
      - IMMICH_API_KEY
      - IMMICH_ALBUM_ID
    restart: unless-stopped

  image-transformer:
    build:
      context: .
      dockerfile: Dockerfile.image-transformer
    volumes:
      - ${ORIGINALS_DIR:-./originals}:/app/originals
      - ${CONVERTED_DIR:-./images}:/app/images
      - ./style:/app/style
    depends_on:
      - immich-fetcher
    environment:
      - CONVERSION_SCRIPT=${CONVERSION_SCRIPT:-convert_image.sh}
    restart: unless-stopped

  image-server:
    build:
      context: .
      dockerfile: Dockerfile.image-server
    ports:
      - "8080:8080"
    volumes:
      - ${CONVERTED_DIR:-./images}:/app/images
    depends_on:
      - image-transformer
    restart: unless-stopped
