# Build stage
FROM rust:1.81 AS builder

WORKDIR /usr/src/app
COPY . .
RUN cargo build --release --bin image-server

# Image for image-server
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /usr/src/app/target/release/image-server /app/

EXPOSE 8080
CMD ["./image-server"]
