# Build stage
FROM rust:1.81 AS builder

WORKDIR /usr/src/app
COPY . .
RUN cargo build --release --bin immich-fetcher

# Image for immich-fetcher
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /usr/src/app/target/release/immich-fetcher /app/

CMD ["./immich-fetcher"]
