version: '3'

services:
  immich-fetcher:
    build:
      context: .
      dockerfile: Dockerfile.immich-fetcher
    volumes:
      - ./originals:/app/originals
    env_file:
      - .env
    restart: unless-stopped

  image-transformer:
    build:
      context: .
      dockerfile: Dockerfile.image-transformer
    volumes:
      - ./originals:/app/originals
      - ./images:/app/images
      - ./style:/app/style
    depends_on:
      - immich-fetcher
    restart: unless-stopped

  image-server:
    build:
      context: .
      dockerfile: Dockerfile.image-server
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
    depends_on:
      - image-transformer
    restart: unless-stopped
