version: '3'

services:
  immich-fetcher:
    build:
      context: .
      target: immich_fetcher
    volumes:
      - ./originals:/app/originals
    env_file:
      - .env

  image-transformer:
    build:
      context: .
      target: image_transformer
    volumes:
      - ./originals:/app/originals
      - ./images:/app/images
    depends_on:
      - immich-fetcher
